export const projects = [
  {
    id: 1,
    title: "Moving - 무빙",
    url: "https://moving-web.site/ko/mover-search",
    color: { bg: "#f1f9ff", text: "#242424" },
    group: "팀",
    date: "2025.07.01 ~ 2025.08.18",
    oneLine:
      "여러 기사님의 견적을 비교하고, 자신에게 가장 적합한 전문가를 선택할 수 있도록 돕는 스마트 이사 비교 플랫폼입니다.",
    skill: {
      frontend: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "date-fns",
        "react-icons",
        "react-hook-form",
        "TanStack Query",
      ],
      backend: [
        "Node.js",
        "Express.js",
        "TypeScript",
        "PostgreSQL",
        "Prisma",
        "Cookie-Parser",
        "bcrypt",
        "JWT",
        "Passport.js",
        "Firebase",
      ],
      deployment: [
        "AWS EC2",
        "AWS RDS",
        "AWS S3",
        "Route 53",
        "Github Actions",
        "Vercel",
      ],
      etc: ["Sentry", "DeepL", "Jest"],
    },
    img: [
      "https://jbinyim12.cafe24.com/img/movingThum.png",
      "https://github.com/user-attachments/assets/a7dc306f-fd4a-49a5-a78c-88b7523cf19b",
      "https://github.com/user-attachments/assets/77e85b0f-6da1-4ffb-8e18-e5e86ca4c0b1",
      "https://github.com/user-attachments/assets/6ff5b0ac-916e-4657-b865-1cf31c72daaf",
      "https://github.com/user-attachments/assets/6ae0fa3a-43b6-4fd5-b5f0-4363d3be046b",
      "https://github.com/user-attachments/assets/07c810ea-87c8-4b07-a80a-e16b3fcfd602",
      "https://github.com/user-attachments/assets/97374679-cf21-487b-ac21-29191689936a",
      "https://github.com/user-attachments/assets/c3a96807-55bf-4328-9b05-549f6e6f2f39",
      "https://github.com/user-attachments/assets/8ff7abca-d4e5-4fca-8a39-5431a0587e2a",
    ],
  },
  {
    id: 2,
    title: "FC전적검색",
    url: "https://www.fcinfo.kr",
    color: { bg: "#242424", text: "#fff" },
    group: "듀오",
    oneLine:
      "FC온라인 게임 전적을 확인하고 유저들과 소통할 수 있는 전적 공유 플랫폼입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/fcinfoThum.png"],
  },
  {
    id: 3,
    title: "공부의 숲",
    url: "https://6-studyforest-phytoncide-fs.netlify.app",
    color: { bg: "#f6f4ef", text: "#242424" },
    group: "팀",
    oneLine:
      "습관을 형성하고, 집중 시간에 따라 포인트를 지급하는 기능을 제공하는 서비스입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/study%402x.png"],
  },
  {
    id: 4,
    title: "최애의 포토",
    url: "https://6-photo-2-fe.vercel.app/market",
    color: { bg: "#0f0f0f", text: "#fff" },
    group: "팀",
    oneLine:
      "디지털 시대의 새로운 수집 문화를 선도하는 디지털 포토카드 거래 플랫폼입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/photoThum.png"],
  },
  {
    id: 5,
    title: "컴패션 - 클론코딩",
    url: "https://compassion-clone.web.app",
    color: { bg: "#005eb8", text: "#fff" },
    group: "솔로",
    oneLine: "기존 컴패션 사이트를 클론 코딩한 사이트입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/compan.png"],
  },
  {
    id: 6,
    title: "연애 내면 테스트 - MBTI",
    url: "https://jb-mbti.firebaseapp.com",
    color: { bg: "#ffeded", text: "#242424" },
    group: "솔로",
    oneLine: "연애 스타일로 자신의 mbti를 확인해 볼 수 있는 사이트입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/mbti.png"],
  },
  {
    id: 7,
    title: "ToDoList",
    url: "https://jb-todolist.firebaseapp.com",
    color: { bg: "#ececec", text: "#242424" },
    group: "솔로",
    oneLine: "리엑트를 이용해 만든 Todo 리스트입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/todolist.png"],
  },
  {
    id: 8,
    title: "꼬리의 일기",
    url: "https://taillife.firebaseapp.com",
    color: { bg: "#4e413a", text: "#fff" },
    group: "솔로",
    oneLine: "반려동물의 일상을 기록하는 기록저장소 입니다.",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/tail.png"],
  },
];
