export const projects = [
  {
    id: 1,
    title: "Moving - 무빙",
    url: "https://moving-web.site/ko/mover-search",
    color: "#f1f9ff",
    skill: [],
    img: [
      "https://jbinyim12.cafe24.com/img/movingThum.png",
      "https://github.com/user-attachments/assets/a7dc306f-fd4a-49a5-a78c-88b7523cf19b",
      "https://github.com/user-attachments/assets/77e85b0f-6da1-4ffb-8e18-e5e86ca4c0b1",
      "https://github.com/user-attachments/assets/6ff5b0ac-916e-4657-b865-1cf31c72daaf",
      "https://github.com/user-attachments/assets/6ae0fa3a-43b6-4fd5-b5f0-4363d3be046b",
      "https://github.com/user-attachments/assets/07c810ea-87c8-4b07-a80a-e16b3fcfd602",
      "https://github.com/user-attachments/assets/97374679-cf21-487b-ac21-29191689936a",
      "https://github.com/user-attachments/assets/c3a96807-55bf-4328-9b05-549f6e6f2f39",
      "https://github.com/user-attachments/assets/8ff7abca-d4e5-4fca-8a39-5431a0587e2a",
    ],
  },
  {
    id: 2,
    title: "FC전적검색",
    url: "https://www.fcinfo.kr",
    color: "#242424",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/fcinfoThum.png"],
  },
  {
    id: 3,
    title: "공부의 숲",
    color: "#f6f4ef",
    url: "https://6-studyforest-phytoncide-fs.netlify.app",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/study%402x.png"],
  },
  {
    id: 4,
    title: "최애의 포토",
    url: "https://6-photo-2-fe.vercel.app/market",
    color: "#0f0f0f",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/photoThum.png"],
  },
  {
    id: 5,
    title: "컴패션",
    url: "https://compassion-clone.web.app",
    color: "#005eb8",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/compan.png"],
  },
  {
    id: 6,
    title: "연애 내면 테스트 - MBTI",
    url: "https://jb-mbti.firebaseapp.com",
    color: "#ffeded",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/mbti.png"],
  },
  {
    id: 7,
    title: "ToDoList",
    url: "https://jb-todolist.firebaseapp.com",
    color: "#ececec",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/todolist.png"],
  },
  {
    id: 8,
    title: "꼬리의 일기",
    url: "https://taillife.firebaseapp.com",
    color: "#4e413a",
    skill: [],
    img: ["https://jbinyim12.cafe24.com/img/tail.png"],
  },
];
